import type { ParsedSchema } from "@/types";

function pascal(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());
}

function base(type: string): string {
  return type.replace(/\(.*\)/, "").toLowerCase().trim();
}

function goType(type: string, nullable: boolean): string {
  const b = base(type);
  let gt: string;
  switch (b) {
    case "int": case "integer": case "smallint": gt = "int"; break;
    case "bigint": case "serial": case "bigserial": gt = "int64"; break;
    case "float": case "real": gt = "float32"; break;
    case "double": case "decimal": case "numeric": gt = "float64"; break;
    case "boolean": case "bool": gt = "bool"; break;
    case "date": case "datetime": case "timestamp": gt = "time.Time"; break;
    case "json": case "jsonb": gt = "datatypes.JSON"; break;
    case "uuid": default: gt = "string"; break;
  }
  return nullable && gt !== "datatypes.JSON" ? `*${gt}` : gt;
}

export function toGORM(schema: ParsedSchema): string {
  if (!schema || schema.tables.length === 0)
    return "// Paste valid DBML and click Parse to generate code.";

  const needsTime = schema.tables.some(t =>
    t.fields.some(f => ["date", "datetime", "timestamp"].includes(base(f.type)))
  );
  const needsDatatypes = schema.tables.some(t =>
    t.fields.some(f => ["json", "jsonb"].includes(base(f.type)))
  );

  const lines: string[] = [
    "// GORM Models — generated by DBML Studio",
    "package models",
    "",
    "import (",
    '\t"gorm.io/gorm"',
  ];
  if (needsTime) lines.push('\t"time"');
  if (needsDatatypes) lines.push('\t"gorm.io/datatypes"');
  lines.push(")", "");

  // Suppress unused import warning if only gorm is needed
  if (!needsTime && !needsDatatypes) {
    lines.push("var _ = gorm.Model{}", "");
  }

  for (const table of schema.tables) {
    const struct = pascal(table.name);
    lines.push(`type ${struct} struct {`);

    for (const f of table.fields) {
      const nullable = !f.isNotNull && !f.isPk;
      const gt = goType(f.type, nullable);
      const fieldName = pascal(f.name);

      const tagParts: string[] = [`column:${f.name}`];
      if (f.isPk) tagParts.push("primaryKey");
      if (f.isIncrement) tagParts.push("autoIncrement");
      const lenM = f.type.match(/\((\d+)\)/);
      const precM = f.type.match(/\((\d+),\s*(\d+)\)/);
      if (lenM && (base(f.type) === "varchar" || base(f.type) === "char")) {
        tagParts.push(`size:${lenM[1]}`);
      }
      if (precM && (base(f.type) === "decimal" || base(f.type) === "numeric")) {
        tagParts.push(`precision:${precM[1]};scale:${precM[2]}`);
      }
      if (f.isNotNull && !f.isPk) tagParts.push("not null");
      if (f.isUnique && !f.isPk) tagParts.push("uniqueIndex");
      if (f.default !== null && !f.isIncrement) tagParts.push(`default:${f.default}`);

      const pad = " ".repeat(Math.max(1, 20 - fieldName.length));
      lines.push(`\t${fieldName}${pad}${gt}\t\`gorm:"${tagParts.join(";")}"\``);
    }

    // Relationship fields
    const gormOutRefs = schema.refs.filter(r => r.from.startsWith(table.name + ".") && (r.type === ">" || r.type === "-"));
    const gormInRefs  = schema.refs.filter(r => r.to.startsWith(table.name + ".") && r.type === ">");
    if (gormOutRefs.length > 0 || gormInRefs.length > 0) {
      lines.push("");
      for (const ref of gormOutRefs) {
        const toTable   = ref.to.split(".")[0];
        const fromPascal = pascal(ref.from.split(".")[1]);
        const toFieldPascal = pascal(ref.to.split(".")[1]);
        const relStruct = pascal(toTable);
        const fPad = " ".repeat(Math.max(1, 20 - relStruct.length));
        const ann = ref.type === "-" ? "constraint:OnUpdate:CASCADE,OnDelete:SET NULL" : "";
        const tag = ann
          ? `gorm:"foreignKey:${fromPascal};references:${toFieldPascal};${ann}"`
          : `gorm:"foreignKey:${fromPascal};references:${toFieldPascal}"`;
        lines.push(`\t${relStruct}${fPad}${relStruct}\t\`${tag}\``);
      }
      for (const ref of gormInRefs) {
        const fromTable  = ref.from.split(".")[0];
        const fromPascal = pascal(ref.from.split(".")[1]);
        const relStruct  = pascal(fromTable);
        const fieldName  = relStruct + "s";
        const fPad = " ".repeat(Math.max(1, 20 - fieldName.length));
        lines.push(`\t${fieldName}${fPad}[]${relStruct}\t\`gorm:"foreignKey:${fromPascal}"\``);
      }
    }

    lines.push("}");
    lines.push("");
    lines.push(`func (${struct}) TableName() string { return "${table.name}" }`, "");
  }

  return lines.join("\n").trimEnd() + "\n";
}
