import type { ParsedSchema } from "@/types";

function snakeToStudly(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());
}

function base(type: string): string {
  return type.replace(/\(.*\)/, "").toLowerCase().trim();
}

function laravelColumn(
  f: Pick<import("@/types").DBMLField, "name" | "type" | "isPk" | "isIncrement" | "isNotNull" | "isUnique" | "default">
): string {
  const b = base(f.type);
  const lenM = f.type.match(/\((\d+)\)/);
  const precM = f.type.match(/\((\d+),\s*(\d+)\)/);

  // PK + autoincrement → $table->id()
  if ((f.isPk && f.isIncrement) || b === "serial" || b === "bigserial") {
    return "$table->id()";
  }
  if (f.isPk && b === "uuid") return `$table->uuid('${f.name}')->primary()`;
  if (f.isPk && (b === "int" || b === "integer")) return `$table->integer('${f.name}')->primary()`;
  if (f.isPk) return `$table->string('${f.name}')->primary()`;

  switch (b) {
    case "int": case "integer": return `$table->integer('${f.name}')`;
    case "bigint": return `$table->bigInteger('${f.name}')`;
    case "smallint": return `$table->smallInteger('${f.name}')`;
    case "varchar":
      return lenM ? `$table->string('${f.name}', ${lenM[1]})` : `$table->string('${f.name}')`;
    case "char":
      return lenM ? `$table->char('${f.name}', ${lenM[1]})` : `$table->char('${f.name}')`;
    case "text": return `$table->text('${f.name}')`;
    case "boolean": case "bool": return `$table->boolean('${f.name}')`;
    case "float": case "real": return `$table->float('${f.name}')`;
    case "double": return `$table->double('${f.name}')`;
    case "decimal": case "numeric":
      return precM
        ? `$table->decimal('${f.name}', ${precM[1]}, ${precM[2]})`
        : `$table->decimal('${f.name}')`;
    case "date": return `$table->date('${f.name}')`;
    case "datetime": return `$table->dateTime('${f.name}')`;
    case "timestamp": return `$table->timestamp('${f.name}')`;
    case "time": return `$table->time('${f.name}')`;
    case "json": case "jsonb": return `$table->json('${f.name}')`;
    case "uuid": return `$table->uuid('${f.name}')`;
    default: return `$table->string('${f.name}')`;
  }
}

export function toLaravel(schema: ParsedSchema): string {
  if (!schema || schema.tables.length === 0)
    return "// Paste valid DBML and click Parse to generate code.";

  const blocks: string[] = [
    "<?php",
    "// Laravel Migrations — generated by DBML Studio",
    "",
    "use Illuminate\\Database\\Migrations\\Migration;",
    "use Illuminate\\Database\\Schema\\Blueprint;",
    "use Illuminate\\Support\\Facades\\Schema;",
    "",
  ];

  for (const table of schema.tables) {
    const className = `Create${snakeToStudly(table.name)}Table`;
    blocks.push(`// php artisan make:migration ${className}`);
    blocks.push("return new class extends Migration");
    blocks.push("{");
    blocks.push("    public function up(): void");
    blocks.push("    {");
    blocks.push(`        Schema::create('${table.name}', function (Blueprint $table) {`);

    for (const f of table.fields) {
      const col = laravelColumn(f);
      const isAutoId = (f.isPk && f.isIncrement) || base(f.type) === "serial" || base(f.type) === "bigserial";

      let line = `            ${col}`;
      if (!isAutoId) {
        if (f.isUnique && !f.isPk) line += "->unique()";
        if (!f.isNotNull && !f.isPk) line += "->nullable()";
        if (f.default !== null && !f.isIncrement) {
          const d = f.default;
          line += d === "now()" || d === "current_timestamp"
            ? "->useCurrent()"
            : `->default(${d})`;
        }
      }
      line += ";";
      blocks.push(line);
    }

    blocks.push("        });");
    blocks.push("    }");
    blocks.push("");
    blocks.push("    public function down(): void");
    blocks.push("    {");
    blocks.push(`        Schema::dropIfExists('${table.name}');`);
    blocks.push("    }");
    blocks.push("};\n");
  }

  return blocks.join("\n").trimEnd() + "\n";
}
