import type { ParsedSchema } from "@/types";

const PRISMA_TYPE: Record<string, string> = {
  int:"Int", integer:"Int", bigint:"BigInt", smallint:"Int",
  varchar:"String", text:"String", char:"String",
  boolean:"Boolean", bool:"Boolean",
  float:"Float", double:"Float", decimal:"Decimal", numeric:"Decimal",
  date:"DateTime", datetime:"DateTime", timestamp:"DateTime", time:"DateTime",
  json:"Json", jsonb:"Json", uuid:"String",
};

function pascal(s: string) {
  return s.replace(/_([a-z])/g, (_,c: string) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());
}
function base(type: string) {
  return type.replace(/\(.*\)/, "").replace(/\[\]/, "").toLowerCase();
}

export function toPrisma(schema: ParsedSchema): string {
  const lines: string[] = [];
  lines.push("// Prisma Schema — generated by DBML Studio\n");
  lines.push("generator client {\n  provider = \"prisma-client-js\"\n}\n");
  lines.push("datasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n");

  for (const en of schema.enums) {
    lines.push(`enum ${pascal(en.name)} {`);
    en.values.forEach(v => lines.push(`  ${v}`));
    lines.push("}\n");
  }

  for (const table of schema.tables) {
    const model = pascal(table.name);
    lines.push(`model ${model} {`);

    for (const f of table.fields) {
      const b = base(f.type);
      const pType = PRISMA_TYPE[b] ?? "String";
      const decs: string[] = [];
      if (f.isPk) decs.push("@id");
      if (f.isIncrement) decs.push("@default(autoincrement())");
      else if (b === "uuid" && f.isPk) decs.push("@default(uuid())");
      if (f.isUnique && !f.isPk) decs.push("@unique");
      if (f.default !== null && !f.isIncrement) decs.push(`@default(${f.default})`);
      const len = f.type.match(/varchar\((\d+)\)/i);
      if (len) decs.push(`@db.VarChar(${len[1]})`);
      if (b === "text") decs.push("@db.Text");
      const opt = !f.isNotNull && !f.isPk ? "?" : "";
      const dec = decs.length ? "  " + decs.join(" ") : "";
      lines.push(`  ${f.name.padEnd(22)} ${pType}${opt}${dec ? `  ${dec.trim()}` : ""}`);
    }

    const outRefs = schema.refs.filter(r => r.from.startsWith(table.name + "."));
    const inRefs  = schema.refs.filter(r => r.to.startsWith(table.name + ".") && r.type === "<");

    for (const ref of outRefs) {
      const [,ff] = ref.from.split(".");
      const [tt] = ref.to.split(".");
      lines.push(`  ${tt.padEnd(22)} ${pascal(tt)}?  @relation(fields: [${ff}], references: [id])`);
    }
    for (const ref of inRefs) {
      const [ft] = ref.from.split(".");
      lines.push(`  ${(ft + "s").padEnd(22)} ${pascal(ft)}[]`);
    }

    lines.push(`\n  @@map("${table.name}")`);
    lines.push("}\n");
  }
  return lines.join("\n");
}
