import type { ParsedSchema } from "@/types";

function pascal(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());
}

function base(type: string): string {
  return type.replace(/\(.*\)/, "").toLowerCase().trim();
}

const TS_TYPE: Record<string, string> = {
  int: "number", integer: "number", bigint: "number", smallint: "number",
  serial: "number", bigserial: "number",
  varchar: "string", text: "string", char: "string",
  boolean: "boolean", bool: "boolean",
  float: "number", double: "number", real: "number", decimal: "number", numeric: "number",
  date: "Date", datetime: "Date", timestamp: "Date", time: "string",
  json: "Record<string, unknown>", jsonb: "Record<string, unknown>",
  uuid: "string",
};

function sequelizeType(type: string): string {
  const b = base(type);
  const lenM = type.match(/\((\d+)\)/);
  const precM = type.match(/\((\d+),\s*(\d+)\)/);

  switch (b) {
    case "int": case "integer": case "serial": return "DataTypes.INTEGER";
    case "bigint": case "bigserial": return "DataTypes.BIGINT";
    case "smallint": return "DataTypes.SMALLINT";
    case "varchar": return lenM ? `DataTypes.STRING(${lenM[1]})` : "DataTypes.STRING";
    case "char": return lenM ? `DataTypes.CHAR(${lenM[1]})` : "DataTypes.CHAR";
    case "text": return "DataTypes.TEXT";
    case "boolean": case "bool": return "DataTypes.BOOLEAN";
    case "float": case "real": return "DataTypes.FLOAT";
    case "double": return "DataTypes.DOUBLE";
    case "decimal": case "numeric":
      return precM ? `DataTypes.DECIMAL(${precM[1]}, ${precM[2]})` : "DataTypes.DECIMAL";
    case "date": return "DataTypes.DATEONLY";
    case "datetime": case "timestamp": return "DataTypes.DATE";
    case "json": case "jsonb": return "DataTypes.JSON";
    case "uuid": return "DataTypes.UUID";
    default: return "DataTypes.STRING";
  }
}

export function toSequelize(schema: ParsedSchema): string {
  if (!schema || schema.tables.length === 0)
    return "// Paste valid DBML and click Parse to generate code.";

  const lines: string[] = [
    "// Sequelize Models — generated by DBML Studio",
    "import {",
    "  DataTypes, Model, Sequelize,",
    "  InferAttributes, InferCreationAttributes, CreationOptional",
    "} from 'sequelize';\n",
  ];

  for (const table of schema.tables) {
    const cls = pascal(table.name);

    lines.push(`export class ${cls} extends Model<`);
    lines.push(`  InferAttributes<${cls}>,`);
    lines.push(`  InferCreationAttributes<${cls}>`);
    lines.push(`> {`);

    for (const f of table.fields) {
      const b = base(f.type);
      const tsType = TS_TYPE[b] ?? "string";
      const isAuto = f.isPk || f.isIncrement;
      const opt = isAuto
        ? `CreationOptional<${tsType}>`
        : f.isNotNull
        ? tsType
        : `${tsType} | null`;
      lines.push(`  declare ${f.name}: ${opt};`);
    }

    lines.push("");
    lines.push(`  static initModel(sequelize: Sequelize): typeof ${cls} {`);
    lines.push(`    return ${cls}.init({`);

    for (const f of table.fields) {
      const sqType = sequelizeType(f.type);
      const props: string[] = [`type: ${sqType}`];
      if (f.isPk) props.push("primaryKey: true");
      if (f.isIncrement) props.push("autoIncrement: true");
      if (!f.isNotNull && !f.isPk) props.push("allowNull: true");
      if (f.isUnique && !f.isPk) props.push("unique: true");
      if (f.default !== null && !f.isIncrement) props.push(`defaultValue: ${f.default}`);
      lines.push(`      ${f.name}: { ${props.join(", ")} },`);
    }

    lines.push("    }, {");
    lines.push("      sequelize,");
    lines.push(`      tableName: '${table.name}',`);
    lines.push("      timestamps: false,");
    lines.push("    });");
    lines.push("  }");

    // Associate method
    const seqOutRefs = schema.refs.filter(r => r.from.startsWith(table.name + ".") && r.type === ">");
    const seqInRefs  = schema.refs.filter(r => r.to.startsWith(table.name + ".") && r.type === ">");
    if (seqOutRefs.length > 0 || seqInRefs.length > 0) {
      lines.push("");
      lines.push(`  static associate(models: Record<string, typeof Model>): void {`);
      for (const ref of seqOutRefs) {
        const [, ff] = ref.from.split(".");
        const [tt]   = ref.to.split(".");
        lines.push(`    ${cls}.belongsTo(models.${pascal(tt)}, { foreignKey: '${ff}', as: '${tt}' });`);
      }
      for (const ref of seqInRefs) {
        const [ft, ff] = ref.from.split(".");
        lines.push(`    ${cls}.hasMany(models.${pascal(ft)}, { foreignKey: '${ff}', as: '${ft}s' });`);
      }
      lines.push("  }");
    }
    lines.push(`}\n`);
  }

  return lines.join("\n");
}
