import type { ParsedSchema } from "@/types";

type SQLDialect = "postgresql" | "sqlserver" | "mongodb";

export function toSQL(schema: ParsedSchema, dialect: SQLDialect): string {
  if (dialect === "mongodb") return toMongoDB(schema);
  return toRelationalSQL(schema, dialect);
}

function toRelationalSQL(schema: ParsedSchema, dialect: SQLDialect): string {
  const isMSSQL = dialect === "sqlserver";
  const Q = isMSSQL ? "" : "\"";
  const AI = isMSSQL ? "IDENTITY(1,1)" : "GENERATED ALWAYS AS IDENTITY";
  const lines: string[] = [];

  lines.push(`-- Generated by DBML Studio — ${dialect.toUpperCase()}\n`);

  for (const table of schema.tables) {
    lines.push(`CREATE TABLE ${Q}${table.name}${Q} (`);
    const fieldLines = table.fields.map(f => {
      let sqlType = f.type.replace(/\[\]/g, "").toUpperCase();
      if (isMSSQL) {
        sqlType = sqlType
          .replace(/^BOOLEAN$/, "BIT")
          .replace(/^TEXT$/, "NVARCHAR(MAX)")
          .replace(/^JSONB?$/, "NVARCHAR(MAX)")
          .replace(/^UUID$/, "UNIQUEIDENTIFIER");
      }
      const parts = [`  ${Q}${f.name}${Q} ${sqlType}`];
      if (f.isPk && f.isIncrement) parts.push(AI);
      if (f.isNotNull || f.isPk) parts.push("NOT NULL");
      if (f.isUnique && !f.isPk) parts.push("UNIQUE");
      if (f.isPk) parts.push("PRIMARY KEY");
      if (f.default !== null && !f.isIncrement) parts.push(`DEFAULT ${f.default}`);
      return parts.join(" ");
    });
    lines.push(fieldLines.join(",\n"));
    lines.push(");\n");
  }

  for (const ref of schema.refs) {
    const [ft, ff] = ref.from.split(".");
    const [tt, tf] = ref.to.split(".");
    lines.push(`ALTER TABLE ${Q}${ft}${Q}`);
    lines.push(`  ADD CONSTRAINT ${Q}fk_${ft}_${ff}${Q}`);
    lines.push(`  FOREIGN KEY (${Q}${ff}${Q}) REFERENCES ${Q}${tt}${Q} (${Q}${tf}${Q});\n`);
  }

  return lines.join("\n");
}

function toMongoDB(schema: ParsedSchema): string {
  function pascal(s: string) {
    return s.replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase()).replace(/^\w/, (c: string) => c.toUpperCase());
  }
  function mongoType(type: string): string {
    const b = type.replace(/\(.*\)/g, "").toLowerCase();
    if (["int","integer","bigint","smallint","float","double","decimal","numeric"].includes(b)) return "Number";
    if (["boolean","bool"].includes(b)) return "Boolean";
    if (["date","datetime","timestamp"].includes(b)) return "Date";
    return "String";
  }

  const lines: string[] = [];
  lines.push("// MongoDB / Mongoose Schemas — generated by DBML Studio\n");
  lines.push("const mongoose = require(\'mongoose\');\nconst { Schema } = mongoose;\n");

  for (const table of schema.tables) {
    const name = pascal(table.name);
    lines.push(`const ${name}Schema = new Schema({`);
    for (const f of table.fields) {
      if ((f.name === "id" || f.name === "_id") && f.isPk) {
        lines.push("  // _id is auto-managed by MongoDB");
        continue;
      }
      const parts = [`type: ${mongoType(f.type)}`];
      if (f.isNotNull) parts.push("required: true");
      if (f.isUnique && !f.isPk) parts.push("unique: true");
      if (f.default !== null) parts.push(`default: ${f.default}`);
      lines.push(`  ${f.name}: { ${parts.join(", ")} },`);
    }
    lines.push("}, { timestamps: true });\n");
    lines.push(`const ${name} = mongoose.model(\'${table.name}\', ${name}Schema);\n`);
  }
  return lines.join("\n");
}
